version: 2.1

orbs:
  buildpulse: workshop64/buildpulse@0.2

jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    steps:
      - checkout

      - buildpulse/setup # Set up BuildPulse connection *before* running the test suite

      - run: mkdir -p /tmp/test-results

      - run:
          name: Run unit tests

          command: |
            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
            gotestsum --junitfile /tmp/test-results/gotestsum-report.xml -- $PACKAGE_NAMES

      - buildpulse/upload:
          path: /tmp/test-results
          account-id: 2988 # Replace this value with your BuildPulse account ID
          repository-id: 237812225 # Replace this value with your BuildPulse repository ID
          when-branch-matches: "master"

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
